channels:
  - pythonocc
  - oce
  - dlr-sc
  - conda-forge
  - cadquery
  - defaults
dependencies:
  # jupyter_cadquery
  - python=3.7
  - ipywidgets
  - jupyter
  - jupyterlab
  - notebook
  - numpy
  - oce=0.18.3
  - pip
  - pythonocc-core=0.18.2
  #
  # lumber_sizes
  # - pandas
  - pytest
  - requests
  - requests_cache
  - sidecar
  - beautifulsoup4
  - sympy
  - pip:
    - pytest-cov
    - ipytest
    - tabulate
    - dataclasses
    - git+https://github.com/CadQuery/cadquery.git
    - pythreejs
    - jupyter_cadquery
    # - git+https://github.com/CapableRobot/cqparts
