channels:
  - pythonocc
  - oce
  - dlr-sc
  - conda-forge
  - cadquery
  - defaults
dependencies:
  # jupyter_cadquery
  - python=3.6.8
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyterlab=1.1.4
  - notebook=6.0.1
  - numpy=1.17.2
  - oce=0.18.3
  - pip=19.2.3
  - pythonocc-core=0.18.2
  #
  # lumber_sizes
  # - pandas
  - pytest
  - requests
  - requests_cache
  - beautifulsoup4
  - sympy
  - pip:
    - tabulate
    - dataclasses==0.6
    - git+https://github.com/CadQuery/cadquery.git
    - sidecar==0.3.0
    - pythreejs==2.1.1
    - jupyter_cadquery==0.9.2-rc3
    # - git+https://github.com/CapableRobot/cqparts
